#!/bin/sh

# When you fail to mount, get the file list using systemctl.
MOUNTLIST=`/bin/systemctl --state=failed | /bin/grep -i "\.mount" | /usr/bin/awk '{print $2}'`

# check MOUNTLIST
if [ -n "$MOUNTLIST" ]; then
	# you find the mount file generated by systemd and format it using type and device.
	for x in $MOUNTLIST; do
		echo "mount path : $x"
		MOUNTFILE="/run/systemd/generator/$x"
		echo "mount file : $MOUNTFILE"
		DEVICE=`/bin/grep -i "What\=" $MOUNTFILE`
		echo "device : $DEVICE"
		TYPE=`/bin/grep -i "Type\=" $MOUNTFILE`
		echo "Type : $TYPE"
		/sbin/mkfs.${TYPE#Type=} ${DEVICE#What=}
	done

	# reboot system
	/sbin/reboot
fi
